### ISSUE TITLE
tdp code doesnt work 

### ISSUE THREAD

**Issue by ripplingsnake** [bactaholic/chimeraos-ROG-Ally-tricks#1]
hello the tpd code didnt work threw errors inc permission denied and thats with frzr-unloch and sudo permissions

**Comment by hbbit-dev** [comment]
@ripplingsnake are you still capped at 15W in the QAM? 
I noticed after I did this once I was still capped at 15W. I ended up at some point deleting both ~/steam-patch and ~/src/steam-patch and repeating the process, rebooted and now I can go past 15W. At this point I don't know why this happens but i'm looking into it for a fix.
If you can, please repeat this process on your own device and let me know if it fixes the issue. Also, have you applied any other tweaks/workarounds?

**Comment by ripplingsnake** [comment]
Hello I removed steam patch completely and just use handycon  works fine haven’t had an issue yet. I did the sleep mode and installed Neros 6.5.0 kernel also the power control I installed and set the max to 47 watt I linked the one I used in chimera discord :) you just place it in decky plug ins and then go into the config folder find the rog ally and change the entry to what ever you want , I also have the smokeless bios mode to allow apu to 54watt Regards Marc Gibb On 21 Sep 2023, at 06:19, db ***@***.***> wrote:﻿
@ripplingsnake are you still capped at 15W in the QAM?
I noticed after I did this once I was still capped at 15W. I ended up at some point deleting both ~/steam-patch and ~/src/steam-patch and repeating the process, rebooted and now I can go past 15W. At this point I don't know why this happens but i'm looking into it for a fix.
If you can, please repeat this process on your own device and let me know if it fixes the issue. Also, have you applied any other tweaks/workarounds?

**Comment by hbbit-dev** [comment]
@ripplingsnake I think I found the discrepancy, if you happen to remember, did you make your ExecStart path

`ExecStart=/home/gamer/steam-patch/steam-patch --user=gamer`

or 

`ExecStart=/home/gamer/steam-patch --user=gamer`

The guide, as its written, uses a naming scheme in which the same name is used for both an executable and a folder, and the TDP controls are only repaired when this path is pointed at the executable, as shown in the first example. I will be updating the guide regardless to make this more clear.

Thanks

**Comment by hbbit-dev** [comment]
This has been open for a while with no comment, I believe the error has been fixed via changes to the guide. If this error is still occuring please feel free to open another request.

**Comment by ripplingsnake** [comment]
Thank you 🙏
